# Numpy 

numpy -> numerical python -> helps to create the numpy array of type -> ndarray.

ndarray are different from normal arrays and lists.

1. ndarray are fast and efficient -> as stores values of same type unlike lists (heterogeneous values)
2. scientific computing -> provides built-in formulas for linear algebra, calculus, etc.
3. stores values in a continuous block hence it's fast and optimised, unlike lists which stores data like in a chain (linked list).
4. fast operations due to vectorization concept.

In [1]:
ls = [12, 24, 48]
print(ls)
print(type(ls))

[12, 24, 48]
<class 'list'>


In [2]:
tup = (12, 45, 90)
print(tup)
print(type(tup))

(12, 45, 90)
<class 'tuple'>


In [3]:
isinstance(-10, int)

True

In [4]:
isinstance(ls, list)

True

In [5]:
isinstance(ls, tuple)

False

1. Numpy

In [2]:
# install and import numpy libraray
import numpy as np

In [7]:
# list object
ls = [0, 30, 40, 50]
arr = np.array(ls)

# numpy array
arr

array([ 0, 30, 40, 50])

In [8]:
print("list: ", ls)
print("numpy array: ", arr)

list:  [0, 30, 40, 50]
numpy array:  [ 0 30 40 50]


In [9]:
# checking types 
print(type(ls))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


means, arr is the numpy array type object; and the data in array is belongs to other types as well

In [10]:
# numpy array creation
arr = np.array(['a', 'b', 'c','d'])
print(arr)
print(type(arr))

print()

arr = np.array([ [10, 20], [30, 40]])
print(arr)
print(type(arr))

['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>

[[10 20]
 [30 40]]
<class 'numpy.ndarray'>


In [11]:
# list cannot create such matrix like numpy arrays
ls = [[10, 20], [30, 40]]
ls

[[10, 20], [30, 40]]

##### datatypes in numpy array:

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype='int8')
print(arr)
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype='float32')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7 8]
int8

[1. 2. 3. 4. 5. 6. 7. 8.]
float32


In [14]:
# after array , then use astype()
arr = arr.astype('int16')
arr

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int16)

In [15]:
# using datatype as function
arr = np.float16(arr)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6. 7. 8.]
float16


##### dimensions in numpy array

In [16]:
# checking the dimension of array
print(arr.ndim)

1


In [17]:
arr = np.array(24)
print(arr)
print(arr.ndim)

24
0


In [18]:
arr = np.array([24, 45, 78])
print(arr)
print(arr.ndim)

print()

arr = np.array([10])
print(arr)
print(arr.ndim)

[24 45 78]
1

[10]
1


In [19]:
arr = np.array([ [10, 20], [30, 40] ])
print(arr)
print(arr.ndim)

[[10 20]
 [30 40]]
2


In [20]:
arr = np.array([[[10, 20, 30], [40, 50, 60], [70,80, 90]]])
print(arr)
print(arr.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3


In [24]:
# change the dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8], ndmin=10)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[[[[[1 2 3 4 5 6 7 8]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 8)


In [27]:
arr = np.array( [ [ [10, 20], [30, 40] ], [[50, 60] , [70, 80] ], [[90,100], [110,120]], [[130,140], [150,160]] ] )
print(arr)
print(arr.ndim)
print(arr.shape)
print()
print(arr[0, 1, 0])

[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]

 [[130 140]
  [150 160]]]
3
(4, 2, 2)

30


4 (first dimension) → number of 2D “blocks” (or “matrices”) → depth

2 (second dimension) → number of rows in each block → height

2 (third dimension) → number of columns in each row → width

so, 

***ndim ->*** number of dimensions or axes.

***depth ->*** size of a dimension (or, axes).

In [28]:
arr = np.array([10, 20, 30,40, 50, 60], ndmin = 4)
print(arr)

[[[[10 20 30 40 50 60]]]]


##### shaping

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


shape = (12,) → just 12 elements in a single dimension

You could think of it as 12 columns if you reshape it to 2D: (1, 12)

In [33]:
arr = arr.reshape(1,12)
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2
(1, 12)


In [34]:
arr = arr.reshape(2, 3, 2)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


we can make anyshape, just remember -> product of shapes == number of elements

##### accessing

In [35]:
arr = np.array([10, 20, 30, 40])
print(arr[2])
print(arr[1])

30
20


In [36]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
print(arr[0,1])

2


In [38]:
print(arr[1, 4])

10


##### creating some special arrays:

In [39]:
arr = np.zeros(3)

In [40]:
arr

array([0., 0., 0.])

In [41]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [42]:
arr = np.ones([4,4])

In [43]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
arr = np.eye(3)

In [45]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
arr = np.arange(10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr = np.empty([2, 3])
arr
print(type(arr))

<class 'numpy.ndarray'>


#### Indexing & Slicing

In [3]:
arr = np.array([ [10, 12, 14, 16], [22, 24, 26, 28], [31, 33, 35, 37 ] ])
arr

array([[10, 12, 14, 16],
       [22, 24, 26, 28],
       [31, 33, 35, 37]])

In [4]:
print(arr[1, 2])

26


In [5]:
arr[0, 2]

np.int64(14)

In [6]:
# slicing
arr[:, 1:3]

array([[12, 14],
       [24, 26],
       [33, 35]])

In [7]:
# ls[1:2:step]

In [8]:
arr[::2, 1:3]

array([[12, 14],
       [33, 35]])

In [9]:
# iteration
# rows only
for i in arr:
    print(i)

[10 12 14 16]
[22 24 26 28]
[31 33 35 37]


In [10]:
# nested loop 
for i in arr:
    # [10 12 14 16]
    for j in i:
        print(j)
    print()

10
12
14
16

22
24
26
28

31
33
35
37



In [11]:
list(np.nditer(arr))

[array(10),
 array(12),
 array(14),
 array(16),
 array(22),
 array(24),
 array(26),
 array(28),
 array(31),
 array(33),
 array(35),
 array(37)]

In [12]:
# looping by index numbers and values
for i, d in np.ndenumerate(arr):
    print(i, d)

(0, 0) 10
(0, 1) 12
(0, 2) 14
(0, 3) 16
(1, 0) 22
(1, 1) 24
(1, 2) 26
(1, 3) 28
(2, 0) 31
(2, 1) 33
(2, 2) 35
(2, 3) 37


In [13]:
# coping the original array for modifications
temp = np.copy(arr)

In [14]:
temp[1, 2] = 100

In [15]:
temp

array([[ 10,  12,  14,  16],
       [ 22,  24, 100,  28],
       [ 31,  33,  35,  37]])

In [16]:
arr

array([[10, 12, 14, 16],
       [22, 24, 26, 28],
       [31, 33, 35, 37]])

In [17]:
# arithmetic operations - vectorizations

In [18]:
arr_1 = np.array([2, 4, 6, 8])

In [19]:
arr_1 + 5

array([ 7,  9, 11, 13])

In [20]:
arr + 5

array([[15, 17, 19, 21],
       [27, 29, 31, 33],
       [36, 38, 40, 42]])

In [21]:
arr - 2

array([[ 8, 10, 12, 14],
       [20, 22, 24, 26],
       [29, 31, 33, 35]])

In [22]:
arr * 2

array([[20, 24, 28, 32],
       [44, 48, 52, 56],
       [62, 66, 70, 74]])

In [23]:
arr / 2

array([[ 5. ,  6. ,  7. ,  8. ],
       [11. , 12. , 13. , 14. ],
       [15.5, 16.5, 17.5, 18.5]])

In [24]:
arr // 2

array([[ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [25]:
arr % 2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [26]:
arr ** 2

array([[ 100,  144,  196,  256],
       [ 484,  576,  676,  784],
       [ 961, 1089, 1225, 1369]])

In [27]:
# some more additional aggr / maths functions 

In [28]:
print(np.min(arr))

10


In [29]:
print(np.max(arr))

37


In [30]:
# returns the index of min element after flattening array
print(np.argmin(arr))
[10, 12, 14, 16, 22, 24, ...]

0


[10, 12, 14, 16, 22, 24, Ellipsis]

In [31]:
# returns the index of max. element after flatenning the array
print(np.argmax(temp))

6


In [106]:
# calc. the cummulative sum
print(np.cumsum(arr))

[ 10  22  36  52  74  98 124 152 183 216 251 288]


In [32]:
# reshaping ->  (-1) flattens the array
new_arr = arr.reshape(-1)
new_arr

array([10, 12, 14, 16, 22, 24, 26, 28, 31, 33, 35, 37])

In [33]:
new_arr = new_arr.reshape(4,3)
print(new_arr)
print(new_arr.ndim)
print(new_arr.shape)

[[10 12 14]
 [16 22 24]
 [26 28 31]
 [33 35 37]]
2
(4, 3)


In [35]:
new_arr = new_arr.reshape(3, 2, 2)

In [36]:
print(new_arr)
print(new_arr.ndim)

[[[10 12]
  [14 16]]

 [[22 24]
  [26 28]]

 [[31 33]
  [35 37]]]
3


In [37]:
# finding the element
arr

array([[10, 12, 14, 16],
       [22, 24, 26, 28],
       [31, 33, 35, 37]])

#### searching

In [39]:
# for 1-d data
arr = np.array( [1, 2, 3, 4, 5, 6, 7, 8] )

# returns the index always
x = np.where(arr % 2 == 0)

# gettin values using array name
print(x)
print(arr[x])

(array([1, 3, 5, 7]),)
[2 4 6 8]


In [40]:
for i in x:
    print(i)

[1 3 5 7]


In [41]:
# for 2-d data
arr = np.array( [ [10, 12, 14], [22, 24, 26], [31, 35, 38] ])
arr

array([[10, 12, 14],
       [22, 24, 26],
       [31, 35, 38]])

In [43]:
# it returns the indexes
idx = np.where ( arr > 25 )
print(idx)

# fetching data by indexes
print("values are: ", arr[idx])

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
values are:  [26 31 35 38]


In [44]:
for i in idx:
    print(i)
    for j in i:
        print(j)
    print()

[1 2 2 2]
1
2
2
2

[2 0 1 2]
2
0
1
2



#### sorting

In [45]:
arr_2 = np.array([55, 12, 10, 67, 23, 78])
print(arr_2)

[55 12 10 67 23 78]


In [46]:
np.sort(arr_2)

array([10, 12, 23, 55, 67, 78])

#### filtering

boolean filtering

In [47]:
arr = np.array([12, 10, 24, 11, 89, 66, 35, 10, 6, 81, 35, 42])
arr

array([12, 10, 24, 11, 89, 66, 35, 10,  6, 81, 35, 42])

In [49]:
idx = arr % 2==0
idx

array([ True,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True])

In [51]:
filtered_arr = arr[idx]
filtered_arr

array([12, 10, 24, 66, 10,  6, 42])

In [52]:
# or, by directly like this:
filtered_arr = arr[arr%2==0]
filtered_arr

array([12, 10, 24, 66, 10,  6, 42])